from telegram.ext import ConversationHandler

# Deposit Flow States
CHOOSING_CURRENCY = 1
TYPING_AMOUNT = 2
CHOOSING_METHOD = 3
CHOOSING_CRYPTO = 4
UPLOADING_SCREENSHOT = 5

# Buy Flow States
BUY_CHOOSING_CURRENCY = 6
BUY_CHOOSING_METHOD = 7
BUY_GC_CODE = 8
BUY_SCREENSHOT = 9

END = ConversationHandler.END
