from telegram.ext import ConversationHandler

# Deposit Flow States
CHOOSING_CURRENCY = 1
TYPING_AMOUNT = 2
CHOOSING_METHOD = 3
CHOOSING_CRYPTO = 4
CONFIRM_PAYMENT = 5
UPLOADING_SCREENSHOT = 6

# Buy Flow States
BUY_CHOOSING_CURRENCY = 7
BUY_CHOOSING_METHOD = 8
BUY_CHOOSING_CRYPTO = 9
BUY_CONFIRM_PAYMENT = 10
BUY_GC_CODE = 11
BUY_SCREENSHOT = 12

# Admin States
BROADCAST_WAITING = 20

END = ConversationHandler.END
