from telegram.ext import ConversationHandler

# Deposit Flow States
CHOOSING_CURRENCY = 1
TYPING_AMOUNT = 2
CHOOSING_METHOD = 3
CHOOSING_CRYPTO = 4
RECEIVING_GC_CODE = 5
CONFIRM_PAYMENT = 6
UPLOADING_SCREENSHOT = 7

# Buy Flow States
BUY_CHOOSING_CURRENCY = 8
BUY_CHOOSING_METHOD = 9
BUY_CHOOSING_CRYPTO = 10
BUY_RECEIVING_GC_CODE = 11
BUY_CONFIRM_PAYMENT = 12
BUY_SCREENSHOT = 13

# Admin States
BROADCAST_WAITING = 20

END = ConversationHandler.END
